version: "3.6"

x-base-app-service: &base-app-service
    build:
        args:
            UID: ${UID}
            GID: ${GID}
        context: ..
        dockerfile: docker/app/Dockerfile
    volumes:
        - ..:/app


services:
    app:
        <<: *base-app-service
        command: ["gunicorn",  "-b",  "0.0.0.0:5000", "crypto_analyzer.asgi", "-k", "uvicorn.workers.UvicornWorker"]
        working_dir: /app
        restart: unless-stopped
        ports:
            - 5001:5000

volumes:
    acme:
    staticfiles:
