version: "3.6"

x-base-app-service: &base-app-service
    build:
        args:
            UID: ${UID}
            GID: ${GID}
        context: ..
        dockerfile: docker/app/Dockerfile
    volumes:
        - ..:/app


services:
    app:
        <<: *base-app-service
        command: ["gunicorn",  "-b",  "0.0.0.0:5000", "configuration.asgi", "-k", "uvicorn.workers.UvicornWorker"]
        working_dir: /app/src
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${DOMAIN}"
            - "traefik.port=5000"
            - "traefik.backend.loadbalancer.stickiness=true"
        restart: unless-stopped

    traefik:
        image: traefik:1.7
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
            - acme:/etc/traefik/acme

volumes:
    acme:
    staticfiles:
