version: "3.6"


x-base-app-service: &base-app-service
    depends_on:
        - db
        - redis
    env_file: ../.env
    restart: unless-stopped

services:
    app:
        <<: *base-app-service
        container_name: app

    db:
        environment:
            POSTGRES_USER: "${DATABASE_USER}"
            POSTGRES_PASSWORD: "${DATABASE_PASS}"
        image: postgres:13.3
        restart: unless-stopped
        container_name: db

    redis:
      image: redis:6.2
      restart: unless-stopped
      container_name: redis

    flower:
      image: leberkaas/flower-armed
      ports:
          - "5556:5555"
      environment:
          - CELERY_BROKER_URL=amqp://rabbitmq:5672
          - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
          - redis
          - rabbitmq
      restart: unless-stopped
      container_name: flower

    rabbitmq:
        image: rabbitmq:3.8
        restart: unless-stopped
        container_name: rabbit

    celery:
        <<: *base-app-service
        command: celery -A crypto_analyzer.celery worker --loglevel=$CELERY_WORKER_LOG_LEVEL --autoscale=4,1
        depends_on:
            - redis
            - rabbitmq
        environment:
            - CELERY_BROKER_URL=amqp://rabbitmq:5672
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        container_name: celery
        restart: unless-stopped

    scheduler:
        <<: *base-app-service
        command: python -m crypto_analyzer.scheduler
        container_name: scheduler
        restart: unless-stopped
