version: "3.6"


x-base-app-service: &base-app-service
    depends_on:
        - db
        - redis
    env_file: ../.env
    restart: unless-stopped

services:
    app:
        <<: *base-app-service

    db:
        environment:
            POSTGRES_USER: "${DATABASE_USER}"
            POSTGRES_PASSWORD: "${DATABASE_PASS}"
        image: postgres:13.3
        restart: unless-stopped

    redis:
      image: redis:6.2
      restart: unless-stopped

    flower:
      image: mher/flower:0.9.5  # 'latest' was not compatible
      ports:
          - "5555:5555"
      environment:
          - CELERY_BROKER_URL=amqp://rabbitmq:5672
          - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
          - redis
          - rabbitmq
      restart: unless-stopped

    rabbitmq:
        image: rabbitmq:3.8
        restart: unless-stopped

    celery:
        <<: *base-app-service
        command: celery -A crypto_analyzer.celery worker --loglevel=$CELERY_WORKER_LOG_LEVEL --autoscale=4,1
        depends_on:
            - redis
            - rabbitmq
        environment:
            - CELERY_BROKER_URL=amqp://rabbitmq:5672
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        restart: unless-stopped
