# Generated by Django 3.2.4 on 2022-08-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('spot', 'spot'), ('futures', 'futures')], default='spot', max_length=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.exchange')),
            ],
            options={
                'unique_together': {('name', 'exchange', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ChartAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField(default=None, null=True)),
                ('fired', models.DateTimeField(default=None, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('interval', models.DurationField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'interval', 'timestamp')},
            },
        ),
    ]
