# Generated by Django 3.2.4 on 2025-10-22 13:06

from django.db import migrations, models
import django.db.models.deletion


def populate_kind(apps, schema_editor):
    Ticker = apps.get_model('charts', 'Ticker')
    Ticker.objects.all().update(kind='Spot')

class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chartlastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongShortChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval', models.DurationField()),
                ('long', models.FloatField()),
                ('short', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ticker',
            name='additional_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ticker',
            name='kind',
            field=models.CharField(choices=[('Spot', 'Spot'), ('Futures', 'Futures'), ('OpenInterest', 'Open Interest'), ('FundingRate', 'Funding Rate'), ('PredictedFundingRate', 'Predicted Funding Rate'), ('LongShortRatio', 'Long Short Ratio'), ('LiquidationHistory', 'Liquidation History')], default='spot', max_length=255),
        ),

        migrations.RunPython(populate_kind, migrations.RunPython.noop),

        migrations.AlterUniqueTogether(
            name='ticker',
            unique_together={('name', 'exchange', 'kind')},
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.CheckConstraint(check=models.Q(('kind__in', ['Spot', 'Futures', 'OpenInterest', 'FundingRate', 'PredictedFundingRate', 'LongShortRatio', 'LuquidationHistory'])), name='valid_ticker_type'),
        ),
        migrations.AddField(
            model_name='longshortchart',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker'),
        ),
        migrations.AlterUniqueTogether(
            name='longshortchart',
            unique_together={('ticker', 'interval', 'timestamp')},
        ),
    ]
